### ISSUE TITLE
Doesn't Work?

### ISSUE THREAD

**Issue by machineghost** [aduth/esm-root-loader#6]
This project is exactly what I was looking for (ie. an ESM-friendly replacement for `NODE_PATH="."`) ... except unfortunately it doesn't work.

Here's my setup ...

**index.js**

    import test from 'src/test';
    console.log(test);

**src/test.js**

    export default 5;

When I run:

    node --experimental-loader=esm-root-loader --es-module-specifier-resolution=node index.js

I get:

> Error [ERR_MODULE_NOT_FOUND]: Cannot find package 'src' imported from /home/me/projects/test/index.js
>     at new NodeError (node:internal/errors:329:5)
>     at packageResolve (node:internal/modules/esm/resolve:714:9)
>     at moduleResolve (node:internal/modules/esm/resolve:755:18)
>     at defaultResolve (node:internal/modules/esm/resolve:869:11)
>     at resolve (file:///home/me/projects/test/node_modules/esm-root-loader/index.js:52:9)
>     at async Loader.resolve (node:internal/modules/esm/loader:88:29)
>     at async Loader.getModuleJob (node:internal/modules/esm/loader:241:17)
>     at async ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:59:21)
>     at async Promise.all (index 0)
>     at async link (node:internal/modules/esm/module_job:64:9) {
>   code: 'ERR_MODULE_NOT_FOUND'

Am I missing something?

**Comment by machineghost** [comment]
After re-reading the documentation I realized I needed to do:

    import test from '/src/test'; // prefix a "/"

So, I'd like to repurpose this ticket: the library works great, but is there any way to add an option so that "/" isn't required?  I have a whole project full of imports without that "/", because back when you could use `NODE_PATH="."`, that was how it worked.

**Comment by aduth** [comment]
I'll have to give this a ponder, since it seems like it might be challenging to differentiate an import of `example/a.js` if "example" could be a directory within the project root or a dependency within `node_modules`.

```
node_modules/
├─ example/
│  ├─ a.js
example/
├─ a.js
```

**Comment by machineghost** [comment]
Traditionally I think priority was given to the `NODE_PATH` (ie. root folder), with `node_modules` being the fallback option.

(After all, you can rename the files in your folder to resolve any conflicts that come up, but you can't rename `node_modules`.)

Thanks for considering it.

**Comment by aduth** [comment]
Yeah, with the fallback behavior, it makes things a little more challenging, since currently the implementation is largely deferring to the default module resolution, but with a prefixed specifier. With fallbacks, it may result in touching the file system multiple times, so there's a possible performance cost to consider.

Also worth noting to your earlier point about having a whole project full of imports, it's likely you might need to make updates anyways, since native ES modules don't support extensionless specifiers anymore:

>A file extension must be provided when using the import keyword to resolve relative or absolute specifiers. Directory indexes (e.g. `'./startup/index.js'`) must also be fully specified.

https://nodejs.org/api/esm.html#mandatory-file-extensions

I'm thinking maybe this could be an opt-in feature (e.g. `rootPrefix: false` option) which, when given a specifier that looks like it could be a local file path (includes a file extension), will _try_ to resolve that file locally, and fall back to the default module resolution otherwise. 

How does that sound?

**Comment by machineghost** [comment]
> since native ES modules don't support extensionless specifiers anymore:

That is what the `--es-module-specifier-resolution=node` fixes :)

>How does that sound?

Perfect, thanks.

**Comment by aduth** [comment]
> > since native ES modules don't support extensionless specifiers anymore:
> 
> That is what the `--es-module-specifier-resolution=node` fixes :)

Oh, neat! I hadn't seen that option before. Thanks for sharing.

> > How does that sound?
> 
> Perfect, thanks.

I just published v0.2.0, which includes this feature. Can you take it for a spin and let me know if this will work for you?

Specifically, you can add `"esmRootPrefix": false` to your `package.json`, and then you can use imports without the `/` prefix.

**Comment by machineghost** [comment]
It seemed to work great for my files, but not so much for `node_modules`:

> file:///home/me/myproject/qa/node_modules/chai/index.mjs:1
> import chai from './index.js';
>        ^^^^
> SyntaxError: The requested module './index.js' does not provide an export named 'default'

To be clear, I'm importing `chai` with:

    import { expect } from 'chai';

but that import is coming from within the `chai` package.

**Comment by aduth** [comment]
Ah, good catch, definitely shouldn't be trying to override the resolution behavior for `node_modules`. While I couldn't actually reproduce the issue locally with Chai, I pushed a new version (0.2.1) to avoid touching imports for dependencies, or for explicitly-relative file imports.

**Comment by machineghost** [comment]
Unfortunately that now breaks the root import of my "src" folder:

>Error [ERR_MODULE_NOT_FOUND]: Cannot find package 'src' imported from /home/me/project/qa/index.js

I appreciate all your help in trying to make this work!

**Comment by aduth** [comment]
Hm, interesting. Would you be able to share a bit more about how your project is structured, and how you're running the application?

I tried recreating a scenario based on what you shared, and it seemed to work as expected for me, both with and without the `--experimental-specifier-resolution=node` option:

https://gist.github.com/aduth/0d35e1dbc3eea0786264157450ab3a05/revisions

**Comment by machineghost** [comment]
It's a pretty basic project.  I run it with `mocha -n experimental-loader=esm-root-loader,es-module-specifier-resolution=node index.js`

index.js has this import:

    import expectNoBrokenImages from 'src/expectations/expectNoBrokenImages';

which I'm trying to make work as:

    import expectNoBrokenImages from '/src/expectations/expectNoBrokenImages';

Meanwhile that file has only one import:

    import { expect } from 'chai';

I guess Mocha might be doing something, but it should just be using Node's loading mechanism.

**Comment by aduth** [comment]
Can you double-check that you have `"esmRootPrefix": false` in your `package.json` ? I was able to reproduce the error you're seeing only after removing that from my test example.

**Comment by machineghost** [comment]
Whether I have:

    "esmRootPrefixDisabled": false,

or:

    "esmRootPrefixDisabled": true,

I get the same error:

node:internal/process/esm_loader:74
    internalBinding('errors').triggerUncaughtException(
                              ^

Error [ERR_MODULE_NOT_FOUND]: Cannot find package 'src' imported from
/home/me/project/qa/index.js

**Comment by aduth** [comment]
Sorry for all the back and forth. But can you clarify one thing from your earlier message:

Do your imports look like this?

```js
import expectNoBrokenImages from '/src/expectations/expectNoBrokenImages';
```

Or like this?

```js
import expectNoBrokenImages from 'src/expectations/expectNoBrokenImages';
```

If it's the first, then: You should leave out `esmRootPrefix` from your `package.json`, since that's the default behavior.

If it's the second, then you'll need `"esmRootPrefix": false`.

Also, one point of correction, the `package.json` setting is `esmRootPrefix`, not `esmRootPrefixDisabled`.

**Comment by machineghost** [comment]
Sorry, I can see why this would be unclear.  The working version of the import (which I copied) lacks the "/", but when I'm testing your code I prefix it with the slash.

>Also, one point of correction, the package.json setting is esmRootPrefix, not esmRootPrefixDisabled.

Again my mistake, apologies!

I didn't want to delete (and forget) that option, but I wanted to make the code work in the meantime (and since the Node org hates us I can't comment out things in `package.json` ...) so I added "disabled" as a way of "commenting out" the option.

However, to be clear with a `package.json` that includes:

    "esmRootPrefix": true,

    "test": "mocha -n experimental-loader=esm-root-loader,es-module-specifier-resolution=node index.js"

    "esm-root-loader": "^0.2.1",

And the previously mentioned `index.js` which includes:

    import expectNoBrokenImages from '/src/expectations/expectNoBrokenImages';

I still get the error:

> node:internal/process/esm_loader:74
>     internalBinding('errors').triggerUncaughtException(
>                               ^
> 
> Error [ERR_MODULE_NOT_FOUND]: Cannot find module '/src/expectations/expectNoBrokenImages' imported from /home/my/project/qa/index.js

**Comment by aduth** [comment]
Okay, I think if you remove `"esmRootPrefix": true,` altogether from your `package.json`, it should work. At least, I can reproduce the same error with that present, and it goes away once it's removed.

**Comment by machineghost** [comment]
That worked!  Thanks so much.

Now if I can only figure out how to get VS Code to realize that's a valid path ... ;)

**Comment by machineghost** [comment]
Oh wait, I spoke too soon: it works with the "/" but still not without it :(

I get:

Error [ERR_MODULE_NOT_FOUND]: Cannot find package 'src' imported from /home/me/project/qa/index.js

**Comment by machineghost** [comment]
But ... when I add `"esmRootPrefix": false,` back, it now does work, _without_ the "/".  Perfect!
